### PR TITLE
Check query for single-click bookmarks

### PR DESCRIPTION
**Pull request by pantherman594**
On first load, check the query string in the url, and then automatically go to the page.
e.g. if you bookmark https://emergency.nofap.com/?cat=em&religious=false and click it, it'll go to a random emergency page

### CODE REVIEW

**Comment by jackfischer** [comment]
Hey @PantherMan594 thank you for caring about NoFap and this contribution! 

We actually used to have a bookmarklet setup that did something similar but it got essentially no usage, however it wasn’t publicized very well at all. If we want to add this or something similar is there anything you could suggest to get people on board? 

If we want this feature, which I think is a good idea, adding an endpoint specifically for this purpose that redirects would get us down from three requests to two and might be a bit faster so I’m inclined to do that instead of parsing it in the frontend. However if we did this we’d need a front end change to let people know about it. 

What are your thoughts? Thanks again, and we’d love to get your talent on some other NoFap stuff

**Comment by pantherman594** [comment]
Oh I didn't see that you already had a bookmarklet (huh... it doesn't seem to be working right now)

I do agree that having a specific endpoint (like it is now, though the categories and religious option could also be added) would be faster. For a front-end change, there could be a little button at the bottom right corner of each of the large buttons ("Emergency", "Rejection", etc). If someone hovers over it, it could have a little message like "Drag me to your bookmarks bar for one-click access".

I'd love to help! What needs to be done?

**Comment by jackfischer** [comment]
Argh, I forgot it was still in the readme, just removed.

I just added the endpoint `https://emergency.nofap.com/redirect?cat=em&religious=false`. I like your hover idea. Maybe instead of a button on each, just have one button in the upper right (similar to the religious toggle) that lets you generate your own link to bookmark?

Given the volume of people that use this I'm very sensitive to even minor UX changes. We should do it thoughtfully! Basically, it should be discoverable, but not at all in your face.

Outside of the panic button there’s always stuff to do for NoFap so lets get in touch via email.

**Comment by pantherman594** [comment]
Yeah that would probably be better, now I'm picturing a little external link icon, which expands when you hover over it to reveal a text field with a link, and 4 checkboxes for each category (with multi-category support? So it picks a random one from any of the selected categories). When it expands it could also integrate the religious toggle as part of it.

**Comment by jackfischer** [comment]
I like it! Think you can pull that off?

**Comment by pantherman594** [comment]
Yup, I'll work in it later today.

**Comment by pantherman594** [comment]
Could you add multi category support? Right now the format would be something like `?cat=em+rej` for emergency and rejection

**Comment by jackfischer** [comment]
Just put it up - you can put multiple parameters as in `https://emergency.nofap.com/redirect?cat=em&cat=dep&religious=false`

**Comment by jackfischer** [comment]
Haven't had a chance to look at this yet sorry

**Comment by jackfischer** [comment]
Hey @PantherMan594 , finally got to look at this! I actually can't figure out how to trigger it in the UI but I'm probably being an idiot

**Comment by pantherman594** [comment]
Do you see the icon in the tip right? If you hover over it, it should expand

**Comment by jackfischer** [comment]
Am indeed an idiot, I was on the wrong branch. This is baller, the animations are completely unexpected and beautiful

**Comment by jackfischer** [comment]
A couple points of feedback that if we address we can merge this and get it out to people. 
* Right now if I'm a random user it's not immediately clear to me what's going on in this button, especially since the url to copy/paste gets cut off. Can we give a toast or another box or something with instructions or an explaination of what we're offering?

* I think the transition from the current UI to new might be easier to swallow if the arrow button is below the religious toggle button (the toggle button shifting location is what's currently distracting) Tell me what you think and I hope this wouldn't involve tweaking animations too much :/ 
* Mobile: If you scale the display to a mobile display it gets janky, I think I had CSS to move the toggle a bit on small screens which is probably the problem unfortunately 
* How can we help them bookmark something that instantly redirects? Nontechnical people will struggle with this a lot. As far as I know the only way to even do this is create a bookmark and then manually edit it

**Comment by pantherman594** [comment]
* Instead of a link, we could have a button (which they can drag to their bookmark bar) with a question mark to its right, if someone hovers over the question mark it'll provide instructions/more information
* I would prefer that, since the fact that the religious button, which is larger, is below the bookmark button looks a bit off as well, but then religious button is also a part of the bookmark dialog, so it'd be a bit awkward to animate that as well. I could just duplicate the button (one above the bookmark dialog, one as a part of it, probably at the bottom), do you want to see how that looks?
* Oh whoops I totally forgot about mobile, I'll work on tweaking those
* As part of the aforementioned help dialog, we could also include instructions on how to delete the bookmark and drag in a new one. Not sure what else we could do though... maybe save bookmark settings in a database with ids, and have an interim page where they can pause a timer-ed redirect to edit those settings? I think that'll be a bit overcomplicated though

**Comment by jackfischer** [comment]
* 1 & 4: I like the drag a button or link idea to the bookmarks bar with instructions/explanation - that's perfect. Persisting stuff on the server is definitely overkill; if they want to set this up multiple times they can just do it multiple times
* Sounds great - what if you didn't make the religious toggle part of the bookmarks dropdown? What if it just lived above it on its own? You can just query the state by `religiousCheck` so it almost doesn't need to be removed/readded. Then it doesn't need to be duplicated and animation is simple - how does that sound?
* Cool on mobile.

I also sent you a [PR](https://github.com/PantherMan594/NoFap-Emergency/pull/1/files) not to this repo but actually into your fork to make some of the repetitive JS more concise. We want to keep a really tight codebase so that more great people like you can contribute!

**Comment by pantherman594** [comment]
I decided to hide it completely for mobile, since there isn't an easy way to bookmark the link (at least not with chrome on android).

**Review by jackfischer — APPROVED** [review]
Wonderful

**Pull request merged**
